Code style improvements & signature fixes & usability improvements
ITECOMMPAY/paymentpage-sdk-php pull request #22
Opened 2019-02-07 08:40 UTC by MattRh

Не удалось нормально сделать rebase.

Различные мелкие фиксы код стайла, для того, чтобы проект был однородным.
\+ небольшие улучшения для поддерживаемости кода и удобства сторонней разработки.
Рефакторинг создания подписи для введения поддержки всех фич из документации и упрощения чтения.
Исправлен баг кодирования параметров для payemtnpage.
\+ добавил тест на изменение базового URL у страницы платежа.
Добавлена возможность указывать baseUrl для PaymentPage без создания своего собственного объекта, используя сущность в Gate.
Добавлен тест на ограничение глубины рекурсии при создании подписи.

2019-02-08 11:30 UTC, zhukovra requested changes

2019-02-08 11:30 UTC, zhukovra commented on phpcs.xml.dist
> +        <exclude name="Generic.Files.LineEndings.InvalidEOLChar" />
@MattRh для чего этот exclude?

2019-02-08 15:57 UTC, MattRh commented on phpcs.xml.dist
> +        <exclude name="Generic.Files.LineEndings.InvalidEOLChar" />
Без него жаловался lint на windows, т.к. он ожидает LF, а получает CRLF

2020-12-08 06:18 UTC, MichaliEverson commented on phpcs.xml.dist
> +        <exclude name="Generic.Files.LineEndings.InvalidEOLChar" />
![IMG_20201207_031844564_BURST001.jpg](https://user-images.githubusercontent.com/72212599/101447412-6c8ee300-38e2-11eb-9e58-a94507afd42f.jpg)@MySpaWakt Leave WitMe

2020-12-08 11:02 UTC, zhukovra commented on phpcs.xml.dist
> +        <exclude name="Generic.Files.LineEndings.InvalidEOLChar" />
@sbaronenkov не узнаю тебя в гриме :rofl:

2021-06-15 09:31 UTC, closed without merging