Sdk 1488
ITECOMMPAY/paymentpage-sdk-php pull request #8
Opened 2018-07-19 14:56 UTC by Nastardimus

gate stable alpha version

2018-07-20 08:27 UTC, blakw0lf approved these changes

2018-07-20 10:49 UTC, zhukovra requested changes
### Организационная часть
1. Название PR должно быть осмысленным.
2. Описание PR неплохо было бы сделать тоже более осмысленным.
3. Шуточки вида "1488" имеют место быть в закрытых репозиториях, а не в публичном SDK, PR с этой веткой принят не будет.
4. Название коммитов должны соответствовать изменениям в коде, а не _fucking big commit_ - [help](http://lmgtfy.com/?q=how+to+write+good+commit+message)
5. Все checks должны быть пройдены, в том числе и codeclimate. Пока они не пройдены - кнопка Merge не будет активна.
6. 4 коммита "code style"? Запускаем `composer lint`, исправляем всё, коммитим один раз.
7. Новая функциональность должна быть отражена в виде инструкции в `README.md`, сейчас непонятно как этими нововведениями пользоваться вообще.
8. PHPDoc `@copyright`, `@author` и `@licence` лишние.

### Фактическая часть
1. Облегчить Validator, убрать оттуда ссылки на классы Request.
2. Классы запроса на гейт должны содержать endpoint и правила валидации (хотя это тоже можно разбить на блоки запроса и запихнуть правила туда)
3. Поправить замечания в детальном review.
4. Ну и конечно покрыть код тестами. Один класс в src - один класс в tests.

Для изучения:
- [Guzzle](http://docs.guzzlephp.org/en/stable/) - клиент, который умеет не только в curl, может быть сделать запросы в Gate PSR-7 совместимыми?
- [symfony/validator](https://github.com/symfony/validator) - standalone валидатор
- [Организация валидации в Yii](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/tutorial-core-validators.md)
- [How to write commit message](https://chris.beams.io/posts/git-commit/)
- [Чистый код](https://refactoring.guru/ru/refactoring/what-is-refactoring)

2018-07-20 10:49 UTC, zhukovra commented on src/Gate.php
> +    public function send(string $action, array $params)
Судя по PHPDoc и return type - это void-метод, но это не так.

Плохо:
```php
$gate = new Gate('secret');
$action = '???'; // надо догадаться ещё что сюда вставить
$params = []; // огромный массив параметров для которого надо лезть в дебри кода
$gate->send($action, $params);
```
Лучше:
```php
$gate = new Gate('secret');
$request = new CardSaleRequest();
$request->setPaymentInfo([])->setCustomerInfo([]); // разбиваем на логические части
$gate->send($request);
```
А сам `Gate::send()` будет иметь приблизительно такое содержание:
```php
public function send(GateRequestInterface $request, $baseUrl = 'https://api...'): GateResponse
{
    $sender = new Sender($baseUrl); // делаем это конфигурируемым
    $request->validate(); //throws ValidationException
    $this->signatureHandler->sign($request);
    $response = $sender->send($request); // throws ProcessException (например Curl-ошибки)
    return $response;
}

interface GateRequestInterface() {
    public function validate();
    public function toArray();
}
```

2018-07-20 10:49 UTC, zhukovra commented on src/Gate.php
> +        return $sender->send($action, $request);
send у Sender не принимает аргументов

2018-07-20 10:49 UTC, zhukovra commented on src/Request.php
> +     * @return ArrayObject
Undefined class ArrayObject

2018-07-20 10:49 UTC, zhukovra commented on src/Request.php
> +    public static function getPermittedActions() : array
Этот функция не нужна, если делать только реализованные классы GateRequestInterface. Нет класса - нет запроса на Gate и `Action: {$action} not supported yet` следовательно тоже будет лишним.

2018-07-20 10:49 UTC, zhukovra commented on src/Request.php
> +        switch ($action) {
Почему нельзя сразу создать Request\Sale()? Зачем девелопера заставлять использовать строковую константу? Сколько тут будет `case` в дальнейшем?

2018-07-20 10:49 UTC, zhukovra commented on src/Request.php
> +            self::PAYMENT_CARD_SALE         => self::PAYMENT_CARD_SALE,
Выравнивание массивов лишнее, добавлю это в PHPCS чуть позже.

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Auth.php
> +class Auth extends Sale
### Комментарий для всех классов Request

Класс запроса должен содержать в себе информацию об используемом endpoint и правила валидации этого запроса. Не надо всё это сваливать в класс Validator, это приведёт к огромному, мало поддерживаемому [классу](https://refactoring.guru/ru/smells/large-class).

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Capture.php
> +                $request['general'][$name] = $value;
Большая частота дублирования кода внутри блока `foreach` по классам Request, необходим рефакторинг.

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Capture.php
> +            if (in_array($name, $general)) {
Все функции PHP указываем с указанием корневого неймспейса: `\in_array`

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Refund.php
> +        $payment = array_keys(Validator::$paymentInfo);
`$payment` не используется ниже, зачем это тут?

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Refund.php
> +            } elseif (in_array($name, $card)) {
Нет переменной `$card` в этом скоупе.

2018-07-20 10:49 UTC, zhukovra commented on src/Request/Validator.php
> +class Validator
Уже если мы пишем свой `Validator`, то не должен содержать в себе правила валидации конкретных полей какого-то запроса. Он должен знать как валидировать тот или иной `Constraint`, а не параметры для валидации. Все правила вида `public static $paymentInfo` помещаются в соответствующие классы блоков запроса, из которых состоит GateRequest (GateRequest hasMany RequestBlock's). Эти RequestBlock внутри GateRequest валидируются с помощью `Validator::validate(RequestBlockInterface $block)` (который тут отражён в виде `commonCheck()`). С первого приближения это как-то так.

2018-07-20 10:49 UTC, zhukovra commented on src/Sender.php
> +    const GATE_API_URL = 'https://api.ecommpay.com/v2/';
BaseURL должен быть дефолтным и конфигурируемым, а не жёстко прибитым.

2018-07-20 10:49 UTC, zhukovra commented on src/Sender.php
> +        $curl = curl_init();
Если ты используешь PHP extension, то должен это указать в composer.json.

2018-07-20 10:49 UTC, zhukovra commented on src/Sender.php
> +    public function __construct(string $action, array $request)
Не очень понимаю, зачем это в параметрах конструктора. Это значит, что для нескольких запросов на Gate мы должны создавать по новому экземпляру Sender, но реальной причины для этого я не вижу.

2018-07-24 16:00 UTC, zhukovra commented
@Nastardimus там два бинарных файла лишние в df639bb.

2019-02-07 07:51 UTC, zhukovra commented
Temporarily closed.

2019-02-07 07:51 UTC, closed without merging